name: Tests

on:
  push:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
    branches:
    - 'main'
    - 'release/*'
  pull_request:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']

env:
  RUN_MAVEN_TESTS: "false"

jobs:
  call-reusable-workflow:
    uses: nationalsecurityagency/datawave/.github/workflows/microservice-maven-tests.yaml@conditional-run-maven-tests